import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import { env } from '$env/dynamic/private';
import fmrData from '$lib/data/fmr-county.json';

/** HUD Fair Market Rents (40th-percentile) for a county.
 * Order: live HUD API when HUD_TOKEN is set, else (or on any failure) the bundled
 * county table generated by scripts/build-fmr-data.py — so every US county resolves
 * with zero keys and no runtime network dependency. */

const BUNDLED = fmrData as {
  meta: { year: string; source: string };
  counties: Record<string, number[]>; // [1BR, 2BR]
};

function bundledLookup(stateFips: string, countyFips: string) {
  const row = BUNDLED.counties[stateFips + countyFips];
  if (!row) return null;
  return { r1: row[0], r2: row[1] };
}

export const GET: RequestHandler = async ({ url, fetch, setHeaders }) => {
  const stateFips = url.searchParams.get('state') || '';
  const countyFips = url.searchParams.get('county') || '';
  if (!/^\d{2}$/.test(stateFips) || !/^\d{3}$/.test(countyFips)) {
    throw error(400, 'state (2-digit) and county (3-digit) FIPS are required');
  }

  const fromBundle = () => {
    const hit = bundledLookup(stateFips, countyFips);
    if (!hit) return json({ ok: false, reason: 'not-found' });
    setHeaders({ 'Cache-Control': 'public, max-age=86400, s-maxage=2592000' });
    return json({ ok: true, r1: hit.r1, r2: hit.r2, county: '', year: BUNDLED.meta.year, bundled: true });
  };

  if (!env.HUD_TOKEN) return fromBundle();

  const entityId = `${stateFips}${countyFips}99999`;
  const api = `https://www.huduser.gov/hudapi/public/fmr/data/${entityId}`;

  const avg = (arr: number[]): number | null => {
    const nums = arr.filter((n) => Number.isFinite(n) && n > 0);
    return nums.length ? Math.round(nums.reduce((a, b) => a + b, 0) / nums.length) : null;
  };

  try {
    const res = await fetch(api, {
      headers: { Authorization: `Bearer ${env.HUD_TOKEN}` },
      signal: AbortSignal.timeout(6_000)
    });
    if (!res.ok) return fromBundle();
    const data = await res.json();
    const basic = data?.data?.basicdata;
    if (!basic) return fromBundle();

    let r1: number | null;
    let r2: number | null;
    if (Array.isArray(basic)) {
      r1 = avg(basic.map((b) => Number(b['One-Bedroom'])));
      r2 = avg(basic.map((b) => Number(b['Two-Bedroom'])));
    } else {
      r1 = Number(basic['One-Bedroom']) || null;
      r2 = Number(basic['Two-Bedroom']) || null;
    }
    if (r1 == null && r2 == null) return fromBundle();

    setHeaders({ 'Cache-Control': 'public, max-age=86400, s-maxage=2592000' });
    return json({
      ok: true,
      r1,
      r2,
      county: data?.data?.county_name ?? '',
      year: data?.data?.year ?? '',
      bundled: false
    });
  } catch {
    return fromBundle();
  }
};
