import { json, error } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import fmrData from '$lib/data/fmr-county.json';

/** HUD Fair Market Rents (40th-percentile) for a county, served entirely from the
 * annual snapshot generated by scripts/build-fmr-data.py. */

const BUNDLED = fmrData as {
  meta: { year: string; source: string };
  counties: Record<string, number[]>; // [1BR, 2BR]
};

export const GET: RequestHandler = async ({ url, setHeaders }) => {
  const stateFips = url.searchParams.get('state') || '';
  const countyFips = url.searchParams.get('county') || '';
  if (!/^\d{2}$/.test(stateFips) || !/^\d{3}$/.test(countyFips)) {
    throw error(400, 'state (2-digit) and county (3-digit) FIPS are required');
  }

  const row = BUNDLED.counties[stateFips + countyFips];
  if (!row) return json({ ok: false, reason: 'not-found' });

  setHeaders({ 'Cache-Control': 'public, max-age=86400, s-maxage=2592000' });
  return json({
    ok: true,
    r1: row[0],
    r2: row[1],
    county: '',
    year: BUNDLED.meta.year,
    bundled: true
  });
};
